export class Solicitud {
  id_solicitud: number = 0
  solicitante: String = ''
  correoSolicitante: String = ''
  fechaSolicitud: String = ''
  tipoTicket: String = '' ///
  provedor: String = ''
  motivo: String = ''
  area: String = ''
  descripcion: String = ''
  observaciones: String = ''
  regresa: String = ''
  autorizador: String = ''
  statusAprobacion: String = ''
  comentariosAutorizador: String = '' //
  fechaSalida: String = ''
  nombreProvedor: String = ''
  validarSalida: String = ''
  fechaCompromiso: String = ''
  comentariosCompras: String = '' //
  historialCompras: String = ''
  fechaRegreso: String = ''
  comentariosRegreso: String = ''
  status2: String = ''
  emailSent: String = ''
  nombreImagen:String=''
  etapa:number=0
  nombreImagen2:String=''
}
